apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod
spec:
  hostPID: true
  securityContext:
    privileged: true
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
