podTemplate(containers: [
        containerTemplate(name: 'tufin', image: 'eu.gcr.io/dream-198012/tufin-cloud-deployer:1.0.0-master', command: 'sleep', args: '99d')
    ]) {
    
    node(POD_LABEL) {
            
        checkout scm
            
        stage('build go code') {
            sh 'echo "go build ./..."'
            sh 'sleep 1'
        }

        stage('build docker image'){
            sh 'echo "docker build my-image"'
            sh 'sleep 1'
        }
            
        stage('Tufin SecureCloud integration'){
            container('tufin') {
                stage('SecureCloud workload security check') {
                    withCredentials([string(credentialsId: 'jenkins-securecloud-api-access-key', variable: 'TUFIN_API_ACCESS_KEY')]) {
                        script {
                            filename = '/k8s/app.yaml'

                            final String url = "https://nir.securecloudtestnir.tufin.io/api/v1/orca/model/cross-cluster/workload-risks"
                            final def (String response, int code) =
                                sh(script: "curl -X POST -s -w '\\n%{response_code}' $url -H 'Authorization: Bearer ${TUFIN_API_ACCESS_KEY}' -H 'Content-Type: application/octet-stream' --data-binary '@${WORKSPACE}${filename}'", returnStdout: true)
                                    .trim()
                                    .tokenize("\n")
                            echo "HTTP response status code: $code"
                            echo "$response" >> "${WORKSPACE}${filename}.response.txt"
                            
                            podSecurityContextRisks = sh(script: "jq '[.workloads[].risks?[] | select(.exempted == false)] | unique' ${WORKSPACE}${filename}.response.txt", returnStdout: true)
                            echo "$podSecurityContextRisks" >> "${WORKSPACE}${filename}.podSecurityContextRisks.txt"
                            podSecurityContextRisksCount = sh(script: "jq 'length' ${WORKSPACE}${filename}.podSecurityContextRisks.txt", returnStdout: true)

                            containerSecurityContextRisks = sh(script: "jq '[.workloads[].containers?[].risks?[] | select(.exempted == false)] | unique' ${WORKSPACE}${filename}.response.txt", returnStdout: true)
                            echo "$containerSecurityContextRisks" >> "${WORKSPACE}${filename}.containerSecurityContextRisks.txt"
                            containerSecurityContextRisksCount = sh(script: "jq 'length' ${WORKSPACE}${filename}.containerSecurityContextRisks.txt", returnStdout: true)

                            echo "${podSecurityContextRisksCount} Pod Security Context Risks: ${podSecurityContextRisks}"
                            echo "${containerSecurityContextRisksCount} Container Security Context Risks: ${containerSecurityContextRisks}"
                        }
                    }
                }
            }
        }
    }
}
